install:
  - cinst gitversion.portable -pre -y
  - cinst gitlink -y

platform: Any CPU

configuration: Release

assembly_info:
  patch: false

before_build:
  - nuget restore Source/PropertyTools.AppVeyor.sln
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo
  
build:
  project: Source/PropertyTools.AppVeyor.sln
  verbosity: minimal

after_build:
  - gitlink c:\projects\propertytools -u https://github.com/objorke/propertytools -f Source/PropertyTools.AppVeyor.sln
  - cmd: NuGet pack Source\PropertyTools.Wpf\PropertyTools.Wpf.nuspec -version "%GitVersion_NuGetVersion%" -prop "target=%CONFIGURATION%"

artifacts:
  - path: Output
    name: PropertyTools-$(GitVersion_SemVer)
    type: zip
  - path: '*.nupkg'
    name: PropertyTools-NuGet-$(GitVersion_SemVer)
    type: zip
